apiVersion: apps/v1
kind: Deployment
metadata:
  name: petfriendsshop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petfriendsshop-backend
  template:
    metadata:
      labels:
        app: petfriendsshop-backend
    spec:
      containers:
        - name: petfriendsshop-backend
          image: 811288377093.dkr.ecr.us-west-2.amazonaws.com/petfriendsshop-backend:latest
          ports: 
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
          # env:   # Setting Enviornmental Variables
          #   - name: DB_HOST   # Setting Database host address from configMap
          #     valueFrom :
          #       configMapKeyRef :
          #         name : db-config
          #         key :  host

          #   - name: DB_NAME  # Setting Database name from configMap
          #     valueFrom :
          #       configMapKeyRef :
          #         name : db-config
          #         key :  dbName

          #   - name: DB_USERNAME  # Setting Database username from Secret
          #     valueFrom :
          #       secretKeyRef :
          #         name : mysql-secrets
          #         key :  username

          #   - name: DB_PASSWORD # Setting Database password from Secret
          #     valueFrom :
          #       secretKeyRef :
          #         name : mysql-secrets
          #         key :  password